/* Copyright (c) (2016,2017,2018,2019) Apple Inc. All rights reserved.
 *
 * corecrypto is licensed under Apple Inc.’s Internal Use License Agreement (which
 * is contained in the License.txt file distributed with corecrypto) and only to 
 * people who accept that license. IMPORTANT:  Any license rights granted to you by 
 * Apple Inc. (if any) are limited to internal use within your organization only on 
 * devices and computers you own or control, for the sole purpose of verifying the 
 * security characteristics and correct functioning of the Apple Software.  You may 
 * not, directly or indirectly, redistribute the Apple Software or any portions thereof.
 */

/* Autogenerated file - Use scheme ccdh_gen_gp to regenerate */
#include "ccdh_internal.h"
#include <corecrypto/ccdh_gp.h>

static ccdh_gp_decl_static(768) _ccdh_gp_apple768 =
{
    .hp = {
        .n = ccn_nof(768),
        .bitlen = 768,
        .funcs = CCZP_FUNCS_DEFAULT
    },
    .p = {
        /* prime */
        CCN64_C(ff,ff,ff,ff,ff,ff,ff,ff),CCN64_C(ec,14,ad,08,4d,0a,47,6d),
        CCN64_C(b7,99,6e,88,52,9b,1a,37),CCN64_C(cb,f6,08,fb,89,4c,72,97),
        CCN64_C(33,2d,de,fd,aa,e9,76,63),CCN64_C(bb,13,32,a7,10,44,f8,68),
        CCN64_C(55,2a,24,e1,69,ee,30,91),CCN64_C(66,c5,05,db,be,af,8d,dc),
        CCN64_C(94,61,9e,6e,28,fc,cd,a3),CCN64_C(d4,a0,df,17,fc,cd,b0,9a),
        CCN64_C(65,75,08,9b,a8,f8,37,3b),CCN64_C(ff,ff,ff,ff,ff,ff,ff,ff)
    },
    .recip = {
        /* recip */
        CCN64_C(a7,5d,fd,8e,10,5b,6a,bf),CCN64_C(da,31,ee,f9,23,dd,ff,35),
        CCN64_C(67,86,98,70,b1,e2,39,07),CCN64_C(14,f4,b7,a7,9d,63,7c,90),
        CCN64_C(7f,7f,33,d9,6b,ad,6d,c6),CCN64_C(c3,10,08,58,de,5a,20,bb),
        CCN64_C(d4,59,60,c4,4c,bd,69,d8),CCN64_C(b5,aa,7f,56,e9,17,68,3f),
        CCN64_C(3c,b3,55,75,ec,11,6e,01),CCN64_C(88,aa,9d,fc,63,28,48,9b),
        CCN64_C(9a,8a,f7,64,57,07,c8,c4),CCN64_C(00,00,00,00,00,00,00,00),
        CCN8_C(01)
    },
    .g = {
        /* g */
        CCN64_C(00,00,00,00,00,00,00,02),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN8_C(00)
    },
    .q = {
        /* q */
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN64_C(00,00,00,00,00,00,00,00),
        CCN64_C(00,00,00,00,00,00,00,00),CCN8_C(00)
    },
    .l = 160,
};

ccdh_const_gp_t ccdh_gp_apple768(void)
{
    return (ccdh_const_gp_t)&_ccdh_gp_apple768;
}
